config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users
  
  resources :events, only: [:index, :new, :show, :create, :edit, :update, :destroy] do
    resources :attendances, only: [:index, :new, :create]
    resources :event_images, only: [:create]
  end
  root to: 'events#index'
  resources :users, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record copy.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
 
  after_create :attendance_send
  belongs_to :attendee, class_name: 'User'
  belongs_to :event

  def attendance_send
    UserMailer.attendance_email(self.attendee, self.event).deliver_now
  end
end

app/models/event.rb
class Event < ApplicationRecord
  validates :start_date, presence: true
  validates :duration, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :title, presence: true, length: {minimum: 5, maximum: 140}
  validates :description, presence: true, length: {minimum: 20, maximum: 1000}
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 1000 }
  validates :location, presence: true
  validate :start_date_cannot_be_in_the_past
  validate :duration_must_be_multiple_of_5
  has_many :attendances
  has_many :attendees, through: :attendances, class_name: 'User'
  belongs_to :admin, class_name: 'User'
  has_one_attached :event_image

  def start_date_cannot_be_in_the_past
    if start_date.present? && start_date < DateTime.now
      errors.add(:start_date, "ne peut pas être dans le passé!")
    end
  end

  def duration_must_be_multiple_of_5
    if duration.present? && duration % 5 != 0
      errors.add(:duration, "doit être multiple de 5")
    end
  end



  def end_date
    return start_date + duration.minutes
  end
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send
  has_many :administrated_events, foreign_key: 'admin_id', class_name: 'Event'
  has_many :attendances, foreign_key: 'attendee_id'
  has_many :joined_events, through: :attendances, source: :event 

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  def isAttendeeOf(event)
    self.joined_events.any? { |evt| evt == event }
  end

  def isAdminOf(event)
    self.administrated_events.any? { |evt| evt == event }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_devise_parameters, if: :devise_controller?

def configure_devise_parameters
  devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :description, :email, :password, :password_confirmation)}
  devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :description, :email, :password, :password_confirmation)}
end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :index]
  before_action :checkIfCurrentUserIsTheEventAdmin, only: [:index]

  def index
    @event = Event.find(params[:event_id])
  end

  def new
    @event = Event.find(params[:event_id])

  end

  def create
    puts "#" * 300
      event = Event.find(params[:event_id])
      # Amount in cents
    @amount = event.price * 100

    customer = Stripe::Customer.create({
      email: current_user.email,
      source: params[:stripeToken],
    })
    begin
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'eur',
    })
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_event_attendance_path(event.id)
    end
        flash[:success] = "Votre paiement a fonctionné. Vous êtes bien inscrit à l'évènement #{event.title}"
        attendance = Attendance.create(attendee: current_user, event: event, stripe_customer_id: customer.id )
        redirect_to event_path(event.id)
     
  end


  private

  def checkIfCurrentUserIsTheEventAdmin
    if current_user.isAdminOf(Event.find(params[:event_id])) == false
      flash[:error] = "Vous ne pouvez pas accéder à cette page car vous n'êtes pas l'administrateur de cet évènement."
      redirect_to event_path(params[:event_id])
    end 
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end
  
  def create
    # Amount in cents
    @amount = 500
  
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'usd',
    })
  
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/event_images_controller.rb
class EventImagesController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    @event.event_image.attach(params[:event_image])
    redirect_to(event_path(@event.id))
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show, :edit, :update, :destroy]
  before_action :checkIfCurrentUserIsTheEventAdmin, only: [:edit, :update, :destroy]
  def index
    @events = Event.all
  end
  
  def show
    @event = Event.find(params[:id])
    
  end

  def new
    @event = Event.new
  end

  def create
    event_params = params.require(:event).permit(:title, :location, :duration, :start_date, :description, :price)
    event = Event.new(event_params)
    event.admin = current_user
    if event.save
  
      flash[:success]="Votre évènement a bien été créé"
      redirect_to event_path(event.id)
    else
   
    @errors = event.errors
    @event = Event.new
    render :new
    end
    #gossip_params = params.require(:gossip).permit(:title, :content)
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    event = Event.find(params[:id])
    event_params = params.require(:event).permit(:title, :location, :duration, :start_date, :description, :price)
    event.attributes = event_params
    if event.save
      flash[:success]="Votre évènement a bien été modifié"
      redirect_to event_path(event.id)
    else
      @errors = event.errors
      @event = Event.find(params[:id])
      render :edit
    end
  end

  def destroy
    event = Event.find(params[:id])
    Event.destroy(event.id)
    flash[:success]= "Votre évènement a bien été supprimé"
    redirect_to events_path
  end


  private

  def checkIfCurrentUserIsTheEventAdmin
    if current_user.isAdminOf(Event.find(params[:id])) == false
      flash[:error] = "Vous ne pouvez pas accéder à cette page car vous n'êtes pas l'administrateur de cet évènement."
      redirect_to event_path(params[:id])
    end 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def show
    @user = User.find(params[:id])
    if current_user.id != @user.id
      flash[:alert] = "Vous ne pouvez pas accéder à la page de profil d'un autre utilisateur."
      redirect_to events_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
        when 'notice'
          "alert alert-primary"
        when 'success'
          "alert alert-success"
        when 'error'
          "alert alert-danger"
        when 'alert'
          "alert alert-danger"
    end
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/event_image_helper.rb
module EventImageHelper
end

app/helpers/events_controller_helper.rb
module EventsControllerHelper
end

app/views/attendances/index.html.erb
<h1>Page d'administration de l'évènement <%= @event.title %></h1>
<div id="attendees-list">
  <h3>Liste des participants</h3>
  <ul>
    <% @event.attendees.each do |attendee| %>
    <li> Nom : <%= attendee.first_name %> <%= attendee.last_name %> Email: <%= attendee.email %> </li>
    <% end %>
  </ul>
</div>

<div id="edit-event-link">
  <%= link_to "Page d'édition de l'évènement", edit_event_path(@event.id), class: "btn btn-primary" %>
</div>

app/views/attendances/new.html.erb
<h1>Attendances#new</h1>
<p>Find me in app/views/attendances/new.html.erb</p>

<%= form_tag event_attendances_path(@event.id) do %>
<article>
  <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
  <% end %>
  <label class="amount">
      <span>Somme à prélever: <%= @event.price %></span>
  </label>
</article>
 <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Inscription à l'évènement <%= @event.title %>"
          data-amount= "<%= @event.price * 100 %>%"
          data-currency="eur"
          data-locale="fr"></script>
<% end %>

app/views/event_image/create.html.erb
<h1>EventImage#create</h1>
<p>Find me in app/views/event_image/create.html.erb</p>

app/views/events/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
      <% if @errors %>
        <% @errors.messages.each do |message|%>
           <div class="alert alert-danger" role="alert">
            Le champ <%= message[0] %> a le problème suivant: <%= message[1][0] %>
            </div>
        <% end %>
      <% end %>
      <%= form_for @event, url: event_path(@event), action: "update" , html: { class: "form-signin mt-3"} do |f| %>
        <h1 class="h3 mb-3 font-weight-normal text-center">Edition de l'évènement</h1>
        <div class="form-group">
          <%= f.label :title, "Titre de l'évènement" %><br />
          <%= f.text_field :title, autofocus: true, autocomplete: "titre", class: "form-control", value: @event.title %>
        </div>
        <div class="form-group">
          <%= f.label :location, "Ville de l'évènement" %><br />
          <%= f.text_field :location, autocomplete: "Paris", class: "form-control", value: @event.location %>
        </div>
        <div class="form-group">
          <%= f.label :start_date, "Date et heure de l'évènement" %><br />
          <%= f.datetime_field :start_date, min: Date.today, class: "form-control", value: @event.start_date.strftime('%d/%m/%Y à %H:%M') %>
        </div>
        <div class="form-group">
          <%= f.label :duration, "Durée de l'évènement en minutes (multiple de 5)" %><br />
          <%= f.number_field :duration, autocomplete: "50", step:"5", class: "form-control", value: @event.duration %>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, autocomplete: "description", class: "form-control", value: @event.description %>
        </div>
        <div class="form-group">
          <%= f.label :price %><br />
          <%= f.number_field :price, autocomplete: "50", in: 1...1001, class: "form-control", value: @event.price %>
        </div>
        <div class="actions mt-5">
          <%= f.submit "Editer l'évènement", class: "btn btn-lg btn-primary btn-block" %>
        </div>
      <% end %>
    <%= link_to "Supprimer l'évènement", event_path(@event.id), method: "delete", class: "btn btn-lg btn-danger btn-block", data: { confirm: "Etes-vous sûr de vouloir supprimer définitivement cet évènement ?" } %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="jumbotron jumbotron-fluid jumbotron-index paral paralsec1">
<% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>" role="alert">
            <%= value %>
      </div>
<% end %>

        <div class="container">
          <div class="text-center"><p>Bienvenue sur</p><br/> <h1 class="display-1"> EventBriteLike </h1>
          <p class= "lead">Ce site hors du commun vous permettra de vous inscrire à des évènements inutiles afin de faire passer le temps de votre misérable vie ennuyeuse.</p>
          
        </div>
</div>
 <div class= "cards-container">
<% @events.each do |event| %>
  <div class="card text-center text-white bg-dark mb-5 mx-auto">
  <div class="card-header">
    <%= event.start_date.strftime("Le %d/%m/%Y à %H:%M") + " à " + event.location %>
  </div>
  <div class="card-body">
    
    <h2 class="card-title"><%= event.title %></h2>
    <h3 class="pricing-card-title"> <%= event.price %><small class="text-muted"> € </small></h3>
    <p class="card-text"> <%= event.description %></p>
    <%= link_to "Voir le détail", event_path(event.id), class_name: "btn btn-primary" %>
  </div>
  <div class="card-footer text-muted">
    <%= distance_of_time_in_words(event.created_at, DateTime.now) + " ago"%> <br />
    <% if event.admin.first_name && event.admin.last_name %>
    <%= "Créé par " + event.admin.first_name + " " + event.admin.last_name %>
    <% end %>
  </div>
</div>
<% end %>
</div>

app/views/events/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
      <% if @errors %>
        <% @errors.messages.each do |message|%>
           <div class="alert alert-danger" role="alert">
            Le champ <%= message[0] %> a le problème suivant: <%= message[1][0] %>
            </div>
        <% end %>
      <% end %>
      <%= form_for @event, url: events_path(@event), html: { class: "form-signin mt-3" } do |f| %>
        <h1 class="h3 mb-3 font-weight-normal text-center">Nouvel évènement</h1>
        <div class="form-group">
          <%= f.label :title, "Titre de l'évènement" %><br />
          <%= f.text_field :title, autofocus: true, autocomplete: "titre", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :location, "Ville de l'évènement" %><br />
          <%= f.text_field :location, autocomplete: "Paris", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :start_date, "Date et heure de l'évènement" %><br />
          <%= f.datetime_field :start_date, min: Date.today, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :duration, "Durée de l'évènement en minutes (multiple de 5)" %><br />
          <%= f.number_field :duration, autocomplete: "50", step:"5", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, autocomplete: "description", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :price %><br />
          <%= f.number_field :price, autocomplete: "50", in: 1...1001, class: "form-control" %>
        </div>
        <div class="actions mt-5">
          <%= f.submit "Créer l'évènement", class: "btn btn-lg btn-primary btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<!-- Third Parallax Section -->
<div class="jumbotron paral paralsec2">
<% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>" role="alert">
            <%= value %>
      </div>
<% end %>
<h1 class="display-3 text-black"><%= @event.title %></h1>
<h3 class="lead text-black text-center"><%= @event.description %></h3>
<div class=" mx-auto m-5 text-center card border border-secondary rounded text-white bg-dark">
  <% if @event.event_image.attached? %>
    <%= image_tag @event.event_image, alt: "event image", class: "card-img-top" %>
  <% elsif current_user == @event.admin %>
    <h3> Ajouter une photo pour l'évènement </h3>
    <%= form_tag event_event_images_path(@event.id), multipart: true do %>
      <%= file_field_tag :event_image, class: "btn btn-primary" %>
      <%= submit_tag "Envoyer la photo", class: "btn btn-success" %>
    <% end %>
  <% end %>
          <h2 class="card-header"><%= @event.price %><small class="text-muted"> € </small></h2>
          <div class="card-body">
              <p >Ville: <%= @event.location %></p>
          <p >Durée: <%= @event.duration %> minutes</p>
          <p>Début : <%= @event.start_date.strftime("Le %d/%m/%Y à %H:%M")%></p>
          <p>Fin: <%= @event.end_date.strftime("Le %d/%m/%Y à %H:%M") %></p>
          </div>
          
          <div class="card-footer">
          <p>Nombre d'inscrits: <%= @event.attendees.length %></p>
          
          <small>Evènement organisé par: <%= @event.admin.email %></small>
          <% if ( current_user != @event.admin && current_user.isAttendeeOf(@event) == false ) %>
            <%= link_to "S'insrire", new_event_attendance_path(@event), class: "btn btn-primary" %>
          <% elsif current_user == @event.admin %>
            <%= link_to "Page d'administration de l'évènement", event_attendances_path(@event), class: "btn btn-primary" %>
          <% end %>
          </div>
        </div>
</div>
        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbritepostgresql</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link href="http://fonts.googleapis.com/css?family=Corben:bold" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Arapey&display=swap" rel="stylesheet">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  </head>

  <body>

 <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse " id="navbarTogglerDemo01">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                 <%= link_to "Accueil", events_path, class: "nav-link"%> 
            </li>
            <li class="nav-item">
                 <%= link_to "Créer un évènement", new_event_path, class: "nav-link"%> 
            </li>
        </ul>
    </div>
    <div class="navbar-collapse ">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Profil</a>
                  <div class="dropdown-menu dropdown-menu-right">
                    <% if user_signed_in? %>
                      <%= link_to "Mon profil", user_path(current_user), class: "dropdown-item"%> 
                      <%= button_to "Se déconnecter", destroy_user_session_path, method: "delete", class: "dropdown-item" %> 
                    <% else %>
       
                      <%= link_to "S'inscrire", new_user_registration_path, class: "dropdown-item"%> 
                      <%= link_to "Se connecter", new_user_session_path, class: "dropdown-item" %> 
                    <% end %>
                    </div>      
            </li>
        </ul>
    </div>
</nav>
    
    <%= yield %>
   
  </body>
</html>

app/views/users/show.html.erb
<div class="jumbotron jumbotron-fluid jumbotron-user">
  <div class="container">
    <h1 class="display-4"><%= @user.first_name %> <%= @user.last_name %></h1>
    <p class="lead"><%= @user.description%></p>
    <div class="container">
        <!-- Example row of columns -->
        <div class="row">
          <div class="col-md-4">
            <h2>Contact</h2>
            <p>email: <%= @user.email %> </p>
            <%= link_to "Editer vos informations personnelles", edit_user_registration_path %>
          </div>
        </div>

       

      </div>
  </div>
</div>

<% @user.administrated_events.each do |event| %>
  <div class="card text-center text-white bg-dark mb-3 mx-auto">
  <div class="card-header">
    <%= event.start_date.strftime("Le %d/%m/%Y à %H:%M") + " à " + event.location %>
  </div>
  <div class="card-body">
    <h1 class="card-title pricing-card-title"> <%= event.price %><small class="text-muted"> € </small></h1>
    <h2 class="card-title"><%= event.title %></h2>
    <p class="card-text"> <%= event.description %></p>
    <%= link_to "Voir le détail", event_path(event.id), class_name: "btn btn-primary" %>
  </div>
 
  <div class="card-footer text-muted">
    <%= distance_of_time_in_words(event.created_at, DateTime.now) + " ago"%> <br />
    <%= "Créé par " + event.admin.first_name + " " + event.admin.last_name %>
  </div>
</div>
<% end %>